/*
 * This file was generated automatically by xsubpp version 1.9402 from the 
 * contents of Audio.xs. Do not edit this file, edit Audio.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Audio.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifdef __cplusplus
}
#endif

#include "audio/audio.h"
#include <sys/types.h>

XS(XS_Solaris__Audio_answer_lue)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Solaris::Audio::answer_lue()");
    {
#line 17 "Audio.xs"
	double	RETVAL;
#line 17 "Audio.xs"

	RETVAL = answer_lue();
#line 17 "Audio.xs"
	ST(0) = sv_newmortal();
	sv_setnv(ST(0), (double)RETVAL);
#line 17 "Audio.xs"
#line 17 "Audio.xs"
    }
    XSRETURN(1);
}

XS(XS_Solaris__Audio_audio_init)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Solaris::Audio::audio_init(direct)");
    {
	int	direct = (int)SvIV(ST(0));
#line 21 "Audio.xs"
	int	RETVAL;
#line 21 "Audio.xs"

	RETVAL = audio_init(direct);
#line 21 "Audio.xs"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
#line 21 "Audio.xs"
#line 21 "Audio.xs"
    }
    XSRETURN(1);
}

XS(XS_Solaris__Audio_audio_set_port)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Solaris::Audio::audio_set_port(port)");
    {
	int	port = (int)SvIV(ST(0));
#line 25 "Audio.xs"
#line 25 "Audio.xs"

	audio_set_port(port);
#line 25 "Audio.xs"
#line 25 "Audio.xs"
#line 25 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_set_rate)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Solaris::Audio::audio_set_rate(rate)");
    {
	int	rate = (int)SvIV(ST(0));
#line 29 "Audio.xs"
#line 29 "Audio.xs"

	audio_set_rate(rate);
#line 29 "Audio.xs"
#line 29 "Audio.xs"
#line 29 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_set_gain)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Solaris::Audio::audio_set_gain(gain)");
    {
	int	gain = (int)SvIV(ST(0));
#line 33 "Audio.xs"
#line 33 "Audio.xs"

	audio_set_gain(gain);
#line 33 "Audio.xs"
#line 33 "Audio.xs"
#line 33 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_set_async)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Solaris::Audio::audio_set_async()");
    {
#line 36 "Audio.xs"
	int	RETVAL;
#line 36 "Audio.xs"

	RETVAL = audio_set_async();
#line 36 "Audio.xs"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
#line 36 "Audio.xs"
#line 36 "Audio.xs"
    }
    XSRETURN(1);
}

XS(XS_Solaris__Audio_audio_destroy)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Solaris::Audio::audio_destroy()");
    {
#line 39 "Audio.xs"
#line 39 "Audio.xs"

	audio_destroy();
#line 39 "Audio.xs"
#line 39 "Audio.xs"
#line 39 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_play)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Solaris::Audio::audio_play(sound, n)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
#line 44 "Audio.xs"
	ssize_t	RETVAL;
#line 44 "Audio.xs"

	RETVAL = audio_play(sound, n);
#line 44 "Audio.xs"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
#line 44 "Audio.xs"
#line 44 "Audio.xs"
    }
    XSRETURN(1);
}

XS(XS_Solaris__Audio_audio_flat)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Solaris::Audio::audio_flat(sv, n, level)");
    {
	SV*	sv = ST(0);
	int	n = (int)SvIV(ST(1));
	short	level = (short)SvIV(ST(2));
#line 51 "Audio.xs"
#line 51 "Audio.xs"
#line 52 "Audio.xs"
  int i;	
  short *sound;
  sv_setpv(sv, ""); /* Eek, ugly hack. */
  SvGROW(sv, n * sizeof(short)); 
  SvCUR_set(sv, n * sizeof(short));
  sound = (short *)SvPV(sv,na);
  for(i=0; i < n; i++) {
    sound[i] = level;
  }
#line 60 "Audio.xs"
#line 60 "Audio.xs"
#line 60 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_drum)
{
    dXSARGS;
    if (items != 5)
	croak("Usage: Solaris::Audio::audio_drum(sound, n, base_freq, range_freq, amplitude)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
	int	base_freq = (int)SvIV(ST(2));
	int	range_freq = (int)SvIV(ST(3));
	int	amplitude = (int)SvIV(ST(4));
#line 68 "Audio.xs"
#line 68 "Audio.xs"

	audio_drum(sound, n, base_freq, range_freq, amplitude);
#line 68 "Audio.xs"
#line 68 "Audio.xs"
#line 68 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_drum2)
{
    dXSARGS;
    if (items != 5)
	croak("Usage: Solaris::Audio::audio_drum2(sound, n, base_freq, range_freq, amplitude)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
	int	base_freq = (int)SvIV(ST(2));
	int	range_freq = (int)SvIV(ST(3));
	int	amplitude = (int)SvIV(ST(4));
#line 76 "Audio.xs"
#line 76 "Audio.xs"

	audio_drum2(sound, n, base_freq, range_freq, amplitude);
#line 76 "Audio.xs"
#line 76 "Audio.xs"
#line 76 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_omni_drum)
{
    dXSARGS;
    if (items != 8)
	croak("Usage: Solaris::Audio::audio_omni_drum(dst, dstn, src, srcn, base_freq, range_freq, step_freq, amplitude)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
	int	base_freq = (int)SvIV(ST(4));
	int	range_freq = (int)SvIV(ST(5));
	double	step_freq = (double)SvNV(ST(6));
	double	amplitude = (double)SvNV(ST(7));
#line 87 "Audio.xs"
#line 87 "Audio.xs"

	audio_omni_drum(dst, dstn, src, srcn, base_freq, range_freq, step_freq, amplitude);
#line 87 "Audio.xs"
#line 87 "Audio.xs"
#line 87 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_scale)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Solaris::Audio::audio_scale(sound, n, k)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
	double	k = (double)SvNV(ST(2));
#line 93 "Audio.xs"
#line 93 "Audio.xs"

	audio_scale(sound, n, k);
#line 93 "Audio.xs"
#line 93 "Audio.xs"
#line 93 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_osc_add)
{
    dXSARGS;
    if (items != 4)
	croak("Usage: Solaris::Audio::audio_osc_add(dst, dstn, frequency, amplitude)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	double	frequency = (double)SvNV(ST(2));
	double	amplitude = (double)SvNV(ST(3));
#line 100 "Audio.xs"
#line 100 "Audio.xs"

	audio_osc_add(dst, dstn, frequency, amplitude);
#line 100 "Audio.xs"
#line 100 "Audio.xs"
#line 100 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_table_add)
{
    dXSARGS;
    if (items != 6)
	croak("Usage: Solaris::Audio::audio_table_add(dst, dstn, src, srcn, frequency, amplitude)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
	double	frequency = (double)SvNV(ST(4));
	double	amplitude = (double)SvNV(ST(5));
#line 109 "Audio.xs"
#line 109 "Audio.xs"

	audio_table_add(dst, dstn, src, srcn, frequency, amplitude);
#line 109 "Audio.xs"
#line 109 "Audio.xs"
#line 109 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_table_iadd)
{
    dXSARGS;
    if (items != 6)
	croak("Usage: Solaris::Audio::audio_table_iadd(dst, dstn, src, srcn, frequency, amplitude)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
	double	frequency = (double)SvNV(ST(4));
	double	amplitude = (double)SvNV(ST(5));
#line 118 "Audio.xs"
#line 118 "Audio.xs"

	audio_table_iadd(dst, dstn, src, srcn, frequency, amplitude);
#line 118 "Audio.xs"
#line 118 "Audio.xs"
#line 118 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_add)
{
    dXSARGS;
    if (items != 4)
	croak("Usage: Solaris::Audio::audio_add(dst, dstoff, src, srcn)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstoff = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
#line 125 "Audio.xs"
#line 125 "Audio.xs"

	audio_add(dst, dstoff, src, srcn);
#line 125 "Audio.xs"
#line 125 "Audio.xs"
#line 125 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_linear_env)
{
    dXSARGS;
    if (items != 5)
	croak("Usage: Solaris::Audio::audio_linear_env(sound, x1, y1, x2, y2)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	x1 = (int)SvIV(ST(1));
	double	y1 = (double)SvNV(ST(2));
	int	x2 = (int)SvIV(ST(3));
	double	y2 = (double)SvNV(ST(4));
#line 133 "Audio.xs"
#line 133 "Audio.xs"

	audio_linear_env(sound, x1, y1, x2, y2);
#line 133 "Audio.xs"
#line 133 "Audio.xs"
#line 133 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_exp_env)
{
    dXSARGS;
    if (items != 3)
	croak("Usage: Solaris::Audio::audio_exp_env(sound, n, halflife)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
	double	halflife = (double)SvNV(ST(2));
#line 139 "Audio.xs"
#line 139 "Audio.xs"

	audio_exp_env(sound, n, halflife);
#line 139 "Audio.xs"
#line 139 "Audio.xs"
#line 139 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_table_env)
{
    dXSARGS;
    if (items != 4)
	croak("Usage: Solaris::Audio::audio_table_env(dst, dstn, src, srcn)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
#line 146 "Audio.xs"
#line 146 "Audio.xs"

	audio_table_env(dst, dstn, src, srcn);
#line 146 "Audio.xs"
#line 146 "Audio.xs"
#line 146 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_noise)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Solaris::Audio::audio_noise(sound, n)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
#line 151 "Audio.xs"
#line 151 "Audio.xs"

	audio_noise(sound, n);
#line 151 "Audio.xs"
#line 151 "Audio.xs"
#line 151 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_distort)
{
    dXSARGS;
    if (items != 6)
	croak("Usage: Solaris::Audio::audio_distort(sound, n, in1, out1, in2, out2)");
    {
	short*	sound = (short *)SvPV(ST(0),na);
	int	n = (int)SvIV(ST(1));
	int	in1 = (int)SvIV(ST(2));
	int	out1 = (int)SvIV(ST(3));
	int	in2 = (int)SvIV(ST(4));
	int	out2 = (int)SvIV(ST(5));
#line 160 "Audio.xs"
#line 160 "Audio.xs"

	audio_distort(sound, n, in1, out1, in2, out2);
#line 160 "Audio.xs"
#line 160 "Audio.xs"
#line 160 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_extract_add)
{
    dXSARGS;
    if (items != 4)
	croak("Usage: Solaris::Audio::audio_extract_add(dst, dstn, src, srcoff)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcoff = (int)SvIV(ST(3));
#line 167 "Audio.xs"
#line 167 "Audio.xs"

	audio_extract_add(dst, dstn, src, srcoff);
#line 167 "Audio.xs"
#line 167 "Audio.xs"
#line 167 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_move)
{
    dXSARGS;
    if (items != 5)
	croak("Usage: Solaris::Audio::audio_move(dst, dstoff, src, srcoff, n)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstoff = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcoff = (int)SvIV(ST(3));
	int	n = (int)SvIV(ST(4));
#line 175 "Audio.xs"
#line 175 "Audio.xs"

	audio_move(dst, dstoff, src, srcoff, n);
#line 175 "Audio.xs"
#line 175 "Audio.xs"
#line 175 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_flange)
{
    dXSARGS;
    if (items != 8)
	croak("Usage: Solaris::Audio::audio_flange(dst, dstn, src, srcn, ctl, ctln, frequency, amplitude)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
	short*	ctl = (short *)SvPV(ST(4),na);
	int	ctln = (int)SvIV(ST(5));
	double	frequency = (double)SvNV(ST(6));
	double	amplitude = (double)SvNV(ST(7));
#line 186 "Audio.xs"
#line 186 "Audio.xs"

	audio_flange(dst, dstn, src, srcn, ctl, ctln, frequency, amplitude);
#line 186 "Audio.xs"
#line 186 "Audio.xs"
#line 186 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

XS(XS_Solaris__Audio_audio_phase)
{
    dXSARGS;
    if (items != 8)
	croak("Usage: Solaris::Audio::audio_phase(dst, dstn, src, srcn, ctl, ctln, frequency, amplitude)");
    {
	short*	dst = (short *)SvPV(ST(0),na);
	int	dstn = (int)SvIV(ST(1));
	short*	src = (short *)SvPV(ST(2),na);
	int	srcn = (int)SvIV(ST(3));
	short*	ctl = (short *)SvPV(ST(4),na);
	int	ctln = (int)SvIV(ST(5));
	double	frequency = (double)SvNV(ST(6));
	double	amplitude = (double)SvNV(ST(7));
#line 197 "Audio.xs"
#line 197 "Audio.xs"

	audio_phase(dst, dstn, src, srcn, ctl, ctln, frequency, amplitude);
#line 197 "Audio.xs"
#line 197 "Audio.xs"
#line 197 "Audio.xs"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Solaris__Audio)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Solaris::Audio::answer_lue", XS_Solaris__Audio_answer_lue, file);
        newXS("Solaris::Audio::audio_init", XS_Solaris__Audio_audio_init, file);
        newXS("Solaris::Audio::audio_set_port", XS_Solaris__Audio_audio_set_port, file);
        newXS("Solaris::Audio::audio_set_rate", XS_Solaris__Audio_audio_set_rate, file);
        newXS("Solaris::Audio::audio_set_gain", XS_Solaris__Audio_audio_set_gain, file);
        newXS("Solaris::Audio::audio_set_async", XS_Solaris__Audio_audio_set_async, file);
        newXS("Solaris::Audio::audio_destroy", XS_Solaris__Audio_audio_destroy, file);
        newXS("Solaris::Audio::audio_play", XS_Solaris__Audio_audio_play, file);
        newXS("Solaris::Audio::audio_flat", XS_Solaris__Audio_audio_flat, file);
        newXS("Solaris::Audio::audio_drum", XS_Solaris__Audio_audio_drum, file);
        newXS("Solaris::Audio::audio_drum2", XS_Solaris__Audio_audio_drum2, file);
        newXS("Solaris::Audio::audio_omni_drum", XS_Solaris__Audio_audio_omni_drum, file);
        newXS("Solaris::Audio::audio_scale", XS_Solaris__Audio_audio_scale, file);
        newXS("Solaris::Audio::audio_osc_add", XS_Solaris__Audio_audio_osc_add, file);
        newXS("Solaris::Audio::audio_table_add", XS_Solaris__Audio_audio_table_add, file);
        newXS("Solaris::Audio::audio_table_iadd", XS_Solaris__Audio_audio_table_iadd, file);
        newXS("Solaris::Audio::audio_add", XS_Solaris__Audio_audio_add, file);
        newXS("Solaris::Audio::audio_linear_env", XS_Solaris__Audio_audio_linear_env, file);
        newXS("Solaris::Audio::audio_exp_env", XS_Solaris__Audio_audio_exp_env, file);
        newXS("Solaris::Audio::audio_table_env", XS_Solaris__Audio_audio_table_env, file);
        newXS("Solaris::Audio::audio_noise", XS_Solaris__Audio_audio_noise, file);
        newXS("Solaris::Audio::audio_distort", XS_Solaris__Audio_audio_distort, file);
        newXS("Solaris::Audio::audio_extract_add", XS_Solaris__Audio_audio_extract_add, file);
        newXS("Solaris::Audio::audio_move", XS_Solaris__Audio_audio_move, file);
        newXS("Solaris::Audio::audio_flange", XS_Solaris__Audio_audio_flange, file);
        newXS("Solaris::Audio::audio_phase", XS_Solaris__Audio_audio_phase, file);
    ST(0) = &sv_yes;
    XSRETURN(1);
}
